#token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyMy0wMy0yMCAxNTozNTowMCIsInVzZXJfaWQiOiJtb3V0aGJvbWIiLCJpcCI6IjIyMC4xMzIuODYuODEifQ.uFyOi1tCHEkYae4iH3WrO8xkkgEJcpSXzcJQ9Z8Ez6s'
STAlert = '/Data/STAlert_by_Find'
price_dir = '/Data/price_record/'
margin_dir = '/Data/margin_record/'
investors_dir = '/Data/investors_record/'
chip_dir = '/Data/chips_record/'
revenue_dir = '/Data/revenue_record/'
